import {useEffect,useMemo,useState} from 'react'
import {caseDate,casePath,normalizeSearch,type EditorialCase} from '../lib/editorial'
import {editorialReports} from '../data/editorialReports'
import {candelariaStops} from '../data/candelariaStops'
import {readFavorites,FAVORITES_KEY} from './CaseActions'
const channels=[
 {handle:'chimbadas.raras',url:'https://www.tiktok.com/@chimbadas.raras',signal:'01'},
 {handle:'historiasyespantos',url:'https://www.tiktok.com/@historiasyespantos',signal:'02'},
 {handle:'anapaolaamor',url:'https://www.tiktok.com/@anapaolaamor',signal:'03'},
 {handle:'unlugaroscuro666',url:'https://www.tiktok.com/@unlugaroscuro666',signal:'04'},
]
const NOTEBOOK_KEY='paranormis:bitacora:v1'
const NOTEBOOK_NOTE_KEY='paranormis:bitacora-nota:v1'
const normCity=(city='')=>{const value=normalizeSearch(city);if(value.includes('bogota'))return 'Bogotá D.C.';if(value.includes('medellin'))return 'Medellín';if(value.includes('cali'))return 'Cali';return city.split(' · ')[0].split(',')[0].trim()}
const kindOf=(title:string,description='')=>{const text=normalizeSearch(`${title} ${description}`);if(/ficcion|dramatizad/.test(text))return 'Ficción';if(/leyenda/.test(text))return 'Leyenda';if(/testimonio/.test(text))return 'Testimonio';return 'Relato publicado'}
const phenomenonOf=(title:string,description='')=>{const text=normalizeSearch(`${title} ${description}`);if(/ovni|abduccion|extraterrestre/.test(text))return 'OVNI y luces';if(/fantasma|aparicion|monja|reptiliana|presencia|bruja/.test(text))return 'Apariciones';return 'Otros fenómenos'}
type Item={id:string;title:string;city:string;summary:string;href:string;kind:string;phenomenon:string;audio:boolean;cover:string;date:string;source?:string}
export default function CaseExplorer({cases}:{cases:EditorialCase[]}) {
 const [tab,setTab]=useState('casos'),[search,setSearch]=useState(''),[city,setCity]=useState(''),[phenomenon,setPhenomenon]=useState(''),[audioOnly,setAudioOnly]=useState(false),[onlySaved,setOnlySaved]=useState(false),[saved,setSaved]=useState<string[]>([]),[expanded,setExpanded]=useState(false),[notebook,setNotebook]=useState<string[]>([]),[note,setNote]=useState(''),[notebookMessage,setNotebookMessage]=useState('')
 useEffect(()=>{const sync=()=>setSaved(readFavorites());sync();try{const stored=JSON.parse(localStorage.getItem(NOTEBOOK_KEY)||'[]');if(Array.isArray(stored))setNotebook(stored.filter((id):id is string=>typeof id==='string').slice(0,6));setNote(localStorage.getItem(NOTEBOOK_NOTE_KEY)||'')}catch{};window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync)},[])
 const items=useMemo<Item[]>(()=>[
  ...cases.map(c=>({id:c._id,title:c.title,city:normCity(c.city||c.region?.name),summary:c.freeformDescription,href:casePath(c._id),kind:kindOf(c.title,c.freeformDescription),phenomenon:phenomenonOf(c.title,`${c.freeformDescription} ${c.creature?.name||''}`),audio:!!c.audioUrl,cover:c.creature?.imageUrl||'/images/general.png',date:caseDate(c),source:c.sourceTitle})),
  ...editorialReports.map((r,i)=>({id:`editorial-${r.id}`,title:r.title,city:normCity(r.city),summary:r.summary,href:`/relatos/${r.id}`,kind:kindOf(r.title,`${r.classification} ${r.summary}`),phenomenon:phenomenonOf(r.title,`${r.classification} ${r.summary}`),audio:false,cover:'/images/general.png',date:r.dateNote,source:r.sourceTitle})),
  {id:'ficcion-taxi-1147',title:'El taxi de las 11:47',city:'Bogotá D.C.',summary:'Una pieza de ficción dramatizada inspirada en un testimonio publicado sobre una pasajera fantasma.',href:'/relatos/el-taxi-de-las-1147',kind:'Ficción',phenomenon:'Apariciones',audio:true,cover:'/images/general.png',date:'Relato de ficción · Audio disponible',source:'Infobae · testimonio de referencia'}
 ],[cases])
 const cities=useMemo(()=>Array.from(new Set(items.map(i=>i.city).filter(Boolean))).sort((a,b)=>a.localeCompare(b,'es')),[items])
 const filtered=items.filter(i=>(!city||i.city===city)&&(!phenomenon||i.phenomenon===phenomenon)&&(!audioOnly||i.audio)&&(!onlySaved||saved.includes(i.id))&&normalizeSearch(`${i.title} ${i.city} ${i.summary} ${i.kind} ${i.phenomenon}`).includes(normalizeSearch(search)))
 const visible=expanded?filtered:filtered.slice(0,6)
 const showTaxi=tab==='casos'&&!search&&!city&&!phenomenon&&!audioOnly&&!onlySaved
 const toggleSave=(id:string)=>{try{const ids=readFavorites();const next=ids.includes(id)?ids.filter(x=>x!==id):[id,...ids].slice(0,500);localStorage.setItem(FAVORITES_KEY,JSON.stringify(next));setSaved(next)}catch{}}
 const toggleNotebook=(id:string)=>{const next=notebook.includes(id)?notebook.filter(item=>item!==id):notebook.length<6?[...notebook,id]:null;if(!next){setNotebookMessage('La bitácora admite hasta seis expedientes.');return}try{localStorage.setItem(NOTEBOOK_KEY,JSON.stringify(next));setNotebook(next);setNotebookMessage(next.includes(id)?'Expediente añadido a tu bitácora.':'Expediente retirado de tu bitácora.')}catch{setNotebookMessage('No se pudo guardar en este dispositivo.')}}
 const saveNote=(value:string)=>{setNote(value);try{localStorage.setItem(NOTEBOOK_NOTE_KEY,value)}catch{setNotebookMessage('No se pudo guardar la nota en este dispositivo.')}}
 const notebookItems=notebook.map(id=>items.find(item=>item.id===id)).filter((item):item is Item=>!!item)
 const surprise=()=>{if(filtered.length)location.assign(filtered[Math.floor(Math.random()*filtered.length)].href)}
 const changeTab=(next:string)=>{setTab(next);requestAnimationFrame(()=>document.getElementById(`tab-${next}`)?.focus())}
 return <section className="explore-shell" aria-label="Explorar Paranormis">
  <div className="explore-toolbar"><div role="tablist" aria-label="Sección de explorar" className="explore-tabs">{[['casos','Casos'],['recorridos','Recorridos'],['canales','Canales'],['bitacora','Bitácora']].map(([key,label])=><button id={`tab-${key}`} role="tab" aria-controls={`panel-${key}`} aria-selected={tab===key} tabIndex={tab===key?0:-1} key={key} onKeyDown={e=>{const order=['casos','recorridos','canales','bitacora'];if(e.key==='ArrowRight')changeTab(order[(order.indexOf(tab)+1)%4]);if(e.key==='ArrowLeft')changeTab(order[(order.indexOf(tab)+3)%4]);if(e.key==='Home')changeTab(order[0]);if(e.key==='End')changeTab(order[3])}} onClick={()=>setTab(key)}>{label}{key==='bitacora'&&notebook.length>0&&<span className="explore-tab-count">{notebook.length}</span>}</button>)}</div>{tab==='casos'&&<button className="explore-surprise" onClick={surprise} disabled={!filtered.length}>Sorpréndeme ↗</button>}</div>
  {tab==='casos'&&<div role="tabpanel" id="panel-casos" aria-labelledby="tab-casos"><label className="explore-search">Buscar en el archivo<input type="search" value={search} onChange={e=>{setSearch(e.target.value);setExpanded(false)}} placeholder="Caso, ciudad o fenómeno…"/></label><div className="explore-filters"><label>Ciudad<select value={city} onChange={e=>{setCity(e.target.value);setExpanded(false)}}><option value="">Todas</option>{cities.map(c=><option key={c}>{c}</option>)}</select></label><label>Fenómeno<select value={phenomenon} onChange={e=>{setPhenomenon(e.target.value);setExpanded(false)}}><option value="">Todos</option>{['Apariciones','OVNI y luces','Otros fenómenos'].map(x=><option key={x}>{x}</option>)}</select></label><label className="explore-check"><input type="checkbox" checked={audioOnly} onChange={e=>{setAudioOnly(e.target.checked);setExpanded(false)}}/> Con audio</label><label className="explore-check"><input type="checkbox" checked={onlySaved} onChange={e=>{setOnlySaved(e.target.checked);setExpanded(false)}}/> Favoritos</label></div>
   <div className="explore-count" role="status">{filtered.length} {filtered.length===1?'registro':'registros'} en el archivo</div>{showTaxi&&<article className="taxi-feature" id="expediente-noche"><div><p className="editorial-eyebrow">Ficción dramatizada · Audio</p><h2>El taxi de las 11:47</h2><p>Una pieza de ficción inspirada en un testimonio publicado.</p></div><a href="/relatos/el-taxi-de-las-1147">Abrir relato y audio ↗</a></article>}<div className="explore-grid">{visible.filter(item=>!(showTaxi&&item.id==='ficcion-taxi-1147')).map(item=><article className="explore-card" key={item.id}><a href={item.href} className="explore-card__image"><img src={item.cover} alt="" loading="lazy"/><span>{item.kind}{item.audio?' · Audio':''}</span></a><div className="explore-card__content"><p className="editorial-eyebrow">{item.city}</p><h2><a href={item.href}>{item.title}</a></h2><p>{item.summary}</p><div className="explore-card__bottom"><a className="editorial-link" href={item.href}>Abrir registro ↗</a><button aria-label={`${saved.includes(item.id)?'Quitar de':'Guardar'} favoritos: ${item.title}`} aria-pressed={saved.includes(item.id)} onClick={()=>toggleSave(item.id)}>{saved.includes(item.id)?'★':'☆'}</button></div><button className={`explore-notebook-toggle ${notebook.includes(item.id)?'is-added':''}`} type="button" aria-pressed={notebook.includes(item.id)} onClick={()=>toggleNotebook(item.id)}>{notebook.includes(item.id)?'− Quitar de bitácora':'+ Añadir a bitácora'}</button></div></article>)}</div>{!filtered.length&&<p className="editorial-panel">No hay registros para estos filtros.</p>}{filtered.length>6&&<button className="explore-more" onClick={()=>setExpanded(!expanded)}>{expanded?'Mostrar menos':'Mostrar más'}</button>}</div>}
  {tab==='recorridos'&&<div role="tabpanel" id="panel-recorridos" aria-labelledby="tab-recorridos" className="explore-secondary"><p className="editorial-eyebrow">Recorridos de archivo</p><a href="/recorridos/bogota" className="explore-route"><div><h2>Rutas de lo inexplicable</h2><p>Cinco expedientes y una ruta complementaria por siete lugares e historias de La Candelaria.</p></div><span>ABRIR RECORRIDO ↗</span></a><div className="explore-stop-links"><h3>La Candelaria · siete paradas</h3>{candelariaStops.map((stop,i)=><a key={stop.title} href={`/recorridos/bogota#candelaria-stop-${String(i+1).padStart(2,'0')}`}><span>{String(i+1).padStart(2,'0')}</span>{stop.title} ↗</a>)}<a className="editorial-link" href="/recorridos/bogota#candelaria-title">Abrir sección completa ↗</a></div></div>}
  {tab==='canales'&&<div role="tabpanel" id="panel-canales" aria-labelledby="tab-canales" className="explore-secondary explore-channel-section"><div className="explore-channel-heading"><div><p className="editorial-eyebrow">Frecuencias externas / Archivo abierto</p><h2>Canales paranormales</h2><p>Otras voces que exploran lo extraño. Abre cada señal para visitar su perfil en TikTok.</p></div><span className="explore-channel-stamp">SINTONÍA<br/>ABIERTA</span></div><div className="explore-channels">{channels.map(({handle,url,signal})=><a className="explore-channel-card" key={handle} href={url} target="_blank" rel="noopener noreferrer"><span className="channel-orbit" aria-hidden="true"><i/><b>✳</b></span><span className="explore-channel-card__top"><span>SEÑAL {signal} / TIKTOK</span><span className="channel-live"><i/> EN FRECUENCIA</span></span><strong>@{handle}</strong><span className="explore-channel-card__bottom"><span>CANAL EXTERNO</span><span>ABRIR FRECUENCIA ↗</span></span></a>)}</div><aside className="explore-channel-invitation"><span className="explore-channel-invitation__mark" aria-hidden="true">✦</span><div><p className="editorial-eyebrow">Espacio para nuevas voces</p><h3>Una frecuencia invitada puede aparecer aquí.</h3><p>La sección está preparada para destacar canales independientes en futuras colaboraciones.</p></div><span className="explore-channel-invitation__label">FUTURA<br/>SEÑAL</span></aside></div>}
  {tab==='bitacora'&&<div role="tabpanel" id="panel-bitacora" aria-labelledby="tab-bitacora" className="explore-secondary explore-notebook"><div className="explore-notebook-heading"><div><p className="editorial-eyebrow">Archivo personal / Solo en este dispositivo</p><h2>Tu bitácora de investigación</h2><p>Reúne hasta seis expedientes y compara qué cuentan sus fuentes, fechas y lugares.</p></div><span className="explore-notebook-count">{String(notebookItems.length).padStart(2,'0')}<small> / 06</small></span></div>{notebookItems.length===0?<div className="explore-notebook-empty"><span aria-hidden="true">⌁</span><h3>La primera pista la eliges tú.</h3><p>Añade expedientes desde la sección Casos. Tu selección se guarda únicamente en este navegador.</p><button type="button" onClick={()=>{setTab('casos');requestAnimationFrame(()=>document.getElementById('tab-casos')?.focus())}}>Explorar expedientes ↗</button></div>:<><div className="explore-notebook-list">{notebookItems.map((item,index)=><article className="explore-notebook-entry" key={item.id}><span className="explore-notebook-entry__index">{String(index+1).padStart(2,'0')}</span><div><p className="editorial-eyebrow">{item.kind} · {item.city||'Lugar no precisado'}</p><h3><a href={item.href}>{item.title} ↗</a></h3><p>{item.summary}</p><div className="explore-notebook-meta"><span>Fenómeno: {item.phenomenon}</span><span>{item.date}</span>{item.source&&<span>Fuente: {item.source}</span>}</div></div><button type="button" aria-label={`Quitar ${item.title} de la bitácora`} onClick={()=>toggleNotebook(item.id)}>×</button></article>)}</div><label className="explore-notebook-note">Notas e hipótesis personales<textarea value={note} onChange={event=>saveNote(event.target.value)} maxLength={2000} placeholder="¿Qué patrones observas? Separa tus hipótesis de lo que dicen las fuentes."/><span>{note.length} / 2000 · Guardado localmente</span></label><p className="explore-notebook-disclaimer">Las coincidencias que anotes son observaciones personales; no verifican los relatos ni establecen una conexión entre ellos.</p></>}{notebookMessage&&<p className="explore-notebook-status" role="status">{notebookMessage}</p>}</div>}
 </section>
}
